apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: openrota
  paas.redhat.com/appcode: ${APP_CODE}
message: |-
  Congratulations on Deploying Openrota-backend into Openshift!
metadata:
  name: openrota-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openrota-backend
    labels:
      tier: backend
  spec:
    tags:
      - name: latest
        from:
          kind: DockerImage
          name: docker.io/openrota/openrota-backend:latest-snapshot

- apiVersion: v1
  kind: Service
  metadata:
    name: openrota-backend
    labels:
      tier: backend
  spec:
    selector:
      tier: backend
    ports:
    - name: 8080-http
      port: 8080
      protocol: TCP
      targetPort: 8080
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      shard: external
      tier: backend
    name: openrota-backend
  spec:
    host: openrota-backend-ext.apps.ext.spoke.prod.us-west-2.aws.paas.redhat.com
    port:
      targetPort: 8080-http
    tls:
      termination: edge
    to:
      kind: Service
      name: openrota-backend
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: openrota-backend
    labels:
      tier: backend
  spec:
    replicas: 1
    selector:
      deploymentconfig: openrota-backend
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    template:
      metadata:
        labels:
          deploymentconfig: openrota-backend
          tier: backend
      spec:
        containers:
        - name: openrota-backend
          image: openrota-backend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q//health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - openrota-backend
        from:
          kind: ImageStreamTag
          name: 'openrota-backend:latest'


parameters:
- description: CMDB ID of the application.
  displayName: App Code
  name: APP_CODE
  required: true
  value: OPRO-001
